server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
  #声明这是一个服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#自我保护机制，false关闭
#  server:
#    enable-self-preservation: false